name: DocPlugin
version: 0.1
main: eu.docserver.docplugin.DocPlugin
author: Doc_CoBrA
commands:
    doc_help:
      description: Learn more about Doc's plugin.
      usage: /doc_help
    doc_money:
      description: Show your balance.
      usage: /doc_money
    doc_info:
      description: Get informations on a player.
      usage: /doc_info [player]
    doc_top:
      description: Print top players on server.
      usage: /doc_top [nb (1-20)]
    doc_op:
      description: Admin give op powers to someone.
      usage: /doc_op [player]